// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPx2M-ZhbG1pAuk93GQe9OTeZlk_pIyWo',
    appId: '1:839475981029:web:21540f07dc7396dfb1820c',
    messagingSenderId: '839475981029',
    projectId: 'bancvest-app',
    authDomain: 'bancvest-app.firebaseapp.com',
    storageBucket: 'bancvest-app.appspot.com',
    measurementId: 'G-TFZJ3BY36F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwL5-lXTirmJ_6ztJaZ2AYEiIdBEfQ6I',
    appId: '1:839475981029:android:c281de6b81c537d9b1820c',
    messagingSenderId: '839475981029',
    projectId: 'bancvest-app',
    storageBucket: 'bancvest-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE3-3CrwXkWBWdFTlUPgZWs5R2ILmgb1U',
    appId: '1:839475981029:ios:cfe1f99d9d0f432cb1820c',
    messagingSenderId: '839475981029',
    projectId: 'bancvest-app',
    storageBucket: 'bancvest-app.appspot.com',
    iosClientId: '839475981029-rakktb1irourhpgaecjfo09gkmfbgie8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bancvestApp',
  );
}
